# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile creates a vagrant for developing Coal Mine. The
# Coal Mine source code will be synced within the vagrant in
# /src/coal-mine. All the requirements from requirements.txt and
# requirements_dev.txt will be installed, as will emacs and a mail
# server as in the demo vagrant. Coal Mine will also be installed and
# started -- from the source tree rather than from PyPI. You can
# reinstall as needed with "cd /src/coal-mine && sudo python3 setup.py
# install", but note that this won't kill and restart the server, so
# you may need to do that by hand..

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/vivid64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "..", "/src/coal-mine"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Boy, is it annoying when you start a vagrant at work, then take your
    # laptop home, and the vagrant can't resolve DNS queries anymore.
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :shell, inline: "apt-get dist-upgrade -y"
  config.vm.provision :shell, inline: "debconf-set-selections <<EOF
postfix	postfix/root_address	string	vagrant
postfix	postfix/mynetworks	string	127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
postfix	postfix/mailbox_limit	string	0
postfix	postfix/protocols	select	all
postfix	postfix/recipient_delim	string	+
postfix	postfix/main_mailer_type	select	Local only
postfix	postfix/chattr	boolean	false
postfix	postfix/mailname	string	vagrant-ubuntu-vivid-64
postfix	postfix/destinations	string	vagrant-ubuntu-vivid-64, localhost.localdomain, localhost
EOF"
  config.vm.provision :shell, inline: "apt-get install -y pandoc mongodb-server postfix python3-dev emacs mailutils"
  # Ubuntu's python3-pip package is borked.
  config.vm.provision :shell, inline: "wget -q https://bootstrap.pypa.io/get-pip.py && " \
                                      "python3 get-pip.py"
  config.vm.provision :shell, inline: "pip3 install -r /src/coal-mine/requirements.txt"
  config.vm.provision :shell, inline: "pip3 install -r /src/coal-mine/requirements_dev.txt"
  config.vm.provision :shell, inline: "cd /src/coal-mine && python3 setup.py install"
  config.vm.provision :shell, inline: "test ! -f /etc/coal-mine.ini && cat >/etc/coal-mine.ini <<EOF
[mongodb]
hosts=localhost
database=coal_mine
username=
password=
[email]
sender=root
[logging]
file=/var/log/coal-mine.log
EOF"
  config.vm.provision :shell, inline: "pkill coal-mine && sleep 5; coal-mine &"

  # Enable provisioning with CFEngine. CFEngine Community packages are
  # automatically installed. For example, configure the host as a
  # policy server and optionally a policy file to run:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.am_policy_hub = true
  #   # cf.run_file = "motd.cf"
  # end
  #
  # You can also configure and bootstrap a client to an existing
  # policy server:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.policy_server_address = "10.0.2.15"
  # end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  # config.vm.provision "puppet" do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "default.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { mysql_password: "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
